/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ApiClientProject.Client.SwaggerDateConverter;

namespace ApiClientProject.Model
{
    /// <summary>
    /// CreationUserModel
    /// </summary>
    [DataContract]
    public partial class CreationUserModel :  IEquatable<CreationUserModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreationUserModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreationUserModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreationUserModel" /> class.
        /// </summary>
        /// <param name="DisplayName">DisplayName (required).</param>
        /// <param name="BirthDate">BirthDate (required).</param>
        /// <param name="WorkPeriodStartDate">WorkPeriodStartDate (required).</param>
        /// <param name="PositionId">PositionId (required).</param>
        public CreationUserModel(string DisplayName = default(string), string BirthDate = default(string), string WorkPeriodStartDate = default(string), string PositionId = default(string))
        {
                this.DisplayName = DisplayName;
                this.BirthDate = BirthDate;
                this.WorkPeriodStartDate = WorkPeriodStartDate;
                this.PositionId = PositionId;
        }
        
        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets BirthDate
        /// </summary>
        [DataMember(Name="birthDate", EmitDefaultValue=false)]
        public string BirthDate { get; set; }

        /// <summary>
        /// Gets or Sets WorkPeriodStartDate
        /// </summary>
        [DataMember(Name="workPeriodStartDate", EmitDefaultValue=false)]
        public string WorkPeriodStartDate { get; set; }

        /// <summary>
        /// Gets or Sets PositionId
        /// </summary>
        [DataMember(Name="positionId", EmitDefaultValue=false)]
        public string PositionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreationUserModel {\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  BirthDate: ").Append(BirthDate).Append("\n");
            sb.Append("  WorkPeriodStartDate: ").Append(WorkPeriodStartDate).Append("\n");
            sb.Append("  PositionId: ").Append(PositionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreationUserModel);
        }

        /// <summary>
        /// Returns true if CreationUserModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreationUserModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreationUserModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.BirthDate == input.BirthDate ||
                    (this.BirthDate != null &&
                    this.BirthDate.Equals(input.BirthDate))
                ) && 
                (
                    this.WorkPeriodStartDate == input.WorkPeriodStartDate ||
                    (this.WorkPeriodStartDate != null &&
                    this.WorkPeriodStartDate.Equals(input.WorkPeriodStartDate))
                ) && 
                (
                    this.PositionId == input.PositionId ||
                    (this.PositionId != null &&
                    this.PositionId.Equals(input.PositionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.BirthDate != null)
                    hashCode = hashCode * 59 + this.BirthDate.GetHashCode();
                if (this.WorkPeriodStartDate != null)
                    hashCode = hashCode * 59 + this.WorkPeriodStartDate.GetHashCode();
                if (this.PositionId != null)
                    hashCode = hashCode * 59 + this.PositionId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisplayName (string) maxLength
            if(this.DisplayName != null && this.DisplayName.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be less than 100.", new [] { "DisplayName" });
            }

            // DisplayName (string) minLength
            if(this.DisplayName != null && this.DisplayName.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be greater than 0.", new [] { "DisplayName" });
            }

            yield break;
        }
    }

}
