// <auto-generated />
using System;
using DBRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DBRepository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190318175259_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Models.EntityModels.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new { Id = new Guid("bb28f13b-8ee5-4c59-a927-e269bded4f02"), Name = "Mr. " },
                        new { Id = new Guid("e49ac4a8-c56d-4446-85c1-cd771526859c"), Name = "Mrs." },
                        new { Id = new Guid("e2bba64d-e100-42e3-a506-3c08f3f6181d"), Name = "Master" },
                        new { Id = new Guid("6dbfa58c-1c35-4110-be3d-68fcf2fa8fdd"), Name = "Doctor" },
                        new { Id = new Guid("0b365f91-6b7a-4469-9894-308a20861622"), Name = "Air Marshall" },
                        new { Id = new Guid("036fc1ef-ca78-4f1e-9be9-b9dfaadc8b9e"), Name = "Princess" },
                        new { Id = new Guid("7166816c-80d8-4b9b-b76c-aefda0ebb2b1"), Name = "General" },
                        new { Id = new Guid("7717bf67-12a5-42fd-aa50-facd07bd6449"), Name = "Ms." },
                        new { Id = new Guid("dcd11c63-d581-4188-b926-69afd86de5a6"), Name = "Miss." },
                        new { Id = new Guid("72c0ed90-6bb3-4108-a919-079035aaf62b"), Name = "Dr." }
                    );
                });

            modelBuilder.Entity("Models.EntityModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("PositionId");

                    b.Property<DateTime>("WorkPeriodStartDate");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.EntityModels.User", b =>
                {
                    b.HasOne("Models.EntityModels.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
