// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DBRepository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Models.EntityModels.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Models.EntityModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid?>("PositionId");

                    b.Property<DateTime>("WorkPeriodStartDate");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("ff7e7526-7ba0-4296-8b88-1e92ee26e66e"), BirthDate = new DateTime(1963, 11, 27, 0, 42, 47, 0, DateTimeKind.Unspecified), DisplayName = "U2", WorkPeriodStartDate = new DateTime(2013, 11, 28, 0, 4, 58, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("2f47bb55-c19a-4b74-88c8-e9af23d4043c"), BirthDate = new DateTime(1989, 9, 24, 17, 29, 33, 0, DateTimeKind.Unspecified), DisplayName = "Genesis", WorkPeriodStartDate = new DateTime(2018, 9, 5, 15, 21, 10, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("6b7b7f4e-870a-467b-b720-5b7b51adf3c3"), BirthDate = new DateTime(1987, 10, 16, 14, 49, 37, 0, DateTimeKind.Unspecified), DisplayName = "Lime", WorkPeriodStartDate = new DateTime(2007, 5, 23, 0, 54, 29, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("e0826148-229b-41ba-af76-8851bd1dff91"), BirthDate = new DateTime(1978, 4, 28, 7, 15, 0, 0, DateTimeKind.Unspecified), DisplayName = "Bruce Springsteen", WorkPeriodStartDate = new DateTime(2007, 7, 25, 14, 47, 25, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d3ebe8e9-10bc-498b-a4e8-4879afe4b71e"), BirthDate = new DateTime(1994, 5, 22, 19, 23, 12, 0, DateTimeKind.Unspecified), DisplayName = "Moev", WorkPeriodStartDate = new DateTime(2005, 4, 27, 8, 1, 15, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("1f0a4295-87b2-4ada-852c-bf3c3d158467"), BirthDate = new DateTime(1998, 3, 2, 8, 45, 52, 0, DateTimeKind.Unspecified), DisplayName = "Lighthouse", WorkPeriodStartDate = new DateTime(2010, 6, 6, 17, 5, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d36cc87a-8bc3-4097-882b-4a787c4c9177"), BirthDate = new DateTime(1968, 6, 22, 9, 47, 31, 0, DateTimeKind.Unspecified), DisplayName = "The Midway State", WorkPeriodStartDate = new DateTime(2014, 5, 7, 17, 16, 36, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("0af97238-b9ef-4d32-ae9f-3a6de9bcb86f"), BirthDate = new DateTime(1992, 2, 14, 3, 5, 59, 0, DateTimeKind.Unspecified), DisplayName = "Maharahj", WorkPeriodStartDate = new DateTime(2012, 9, 15, 13, 24, 16, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("1b5ad208-debe-4cee-8c2d-3f2783cc64b7"), BirthDate = new DateTime(1968, 4, 10, 3, 36, 41, 0, DateTimeKind.Unspecified), DisplayName = "Elton John", WorkPeriodStartDate = new DateTime(2013, 7, 14, 13, 33, 41, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("5c105239-a2ae-4bae-9668-6b6b94588d7e"), BirthDate = new DateTime(1995, 3, 15, 21, 13, 36, 0, DateTimeKind.Unspecified), DisplayName = "Bon Jovi", WorkPeriodStartDate = new DateTime(2001, 5, 11, 7, 21, 42, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("2a679d7d-0da9-4877-9552-a56f61ed870d"), BirthDate = new DateTime(1962, 8, 20, 13, 43, 13, 0, DateTimeKind.Unspecified), DisplayName = "Eminem", WorkPeriodStartDate = new DateTime(2007, 9, 14, 3, 38, 10, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("fad63172-5df7-4b34-a43c-a9d35f23bba8"), BirthDate = new DateTime(1972, 6, 14, 7, 15, 48, 0, DateTimeKind.Unspecified), DisplayName = "Mandala", WorkPeriodStartDate = new DateTime(2016, 10, 13, 22, 19, 56, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("7a1c9598-2a76-497a-8b45-3c7604f448a6"), BirthDate = new DateTime(1977, 4, 7, 4, 14, 42, 0, DateTimeKind.Unspecified), DisplayName = "Julio Iglesias", WorkPeriodStartDate = new DateTime(2004, 5, 4, 2, 8, 55, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("a5a7e4c7-ea5c-4a69-ad20-32c8d3d74391"), BirthDate = new DateTime(1986, 1, 8, 12, 52, 58, 0, DateTimeKind.Unspecified), DisplayName = "My Darkest Days", WorkPeriodStartDate = new DateTime(2015, 5, 20, 19, 25, 51, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("f0f6d392-ab94-4463-be7e-2cc277fdf1ce"), BirthDate = new DateTime(1990, 1, 12, 16, 6, 41, 0, DateTimeKind.Unspecified), DisplayName = "Lightning Dust", WorkPeriodStartDate = new DateTime(2014, 7, 14, 19, 28, 9, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d77b0dd3-e55d-47e4-8d1d-fb4f231b3697"), BirthDate = new DateTime(1997, 1, 24, 16, 34, 47, 0, DateTimeKind.Unspecified), DisplayName = "The Musical Box", WorkPeriodStartDate = new DateTime(2003, 11, 4, 22, 11, 54, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("c7b4a61b-0682-48b6-a5f5-712815605d87"), BirthDate = new DateTime(1994, 9, 22, 4, 22, 18, 0, DateTimeKind.Unspecified), DisplayName = "The Lincolns", WorkPeriodStartDate = new DateTime(2011, 8, 3, 1, 23, 13, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("99310f8e-b9dd-46d4-b7a8-611d0dbe9a83"), BirthDate = new DateTime(1984, 7, 2, 15, 58, 2, 0, DateTimeKind.Unspecified), DisplayName = "The Carpenters", WorkPeriodStartDate = new DateTime(2016, 12, 16, 1, 37, 56, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("1fd24e50-8287-4388-bc80-807f433999a9"), BirthDate = new DateTime(1960, 7, 21, 7, 58, 59, 0, DateTimeKind.Unspecified), DisplayName = "Little Caesar and the Consuls", WorkPeriodStartDate = new DateTime(2004, 2, 7, 16, 8, 14, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("eeb7cdbd-7a88-4ed2-855a-becc84b9adf1"), BirthDate = new DateTime(1994, 4, 26, 12, 34, 28, 0, DateTimeKind.Unspecified), DisplayName = "Mes Aïeux", WorkPeriodStartDate = new DateTime(2007, 9, 13, 18, 28, 24, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("8149b3f7-68d9-4596-8752-2fff1057296c"), BirthDate = new DateTime(1965, 1, 27, 21, 10, 52, 0, DateTimeKind.Unspecified), DisplayName = "MSTRKRFT", WorkPeriodStartDate = new DateTime(2011, 7, 4, 0, 6, 32, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("f2fc4a48-3c98-428c-b335-e2063067ccbe"), BirthDate = new DateTime(1988, 6, 22, 4, 25, 43, 0, DateTimeKind.Unspecified), DisplayName = "Land of Talk", WorkPeriodStartDate = new DateTime(2016, 7, 29, 21, 47, 23, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("95cf045e-6c7b-408d-b993-68c3b2f78147"), BirthDate = new DateTime(1987, 4, 16, 18, 24, 0, 0, DateTimeKind.Unspecified), DisplayName = "Garth Brooks", WorkPeriodStartDate = new DateTime(2005, 3, 15, 21, 7, 50, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("3876dbbb-24e7-4032-93df-5f844621e91e"), BirthDate = new DateTime(1971, 1, 4, 8, 22, 0, 0, DateTimeKind.Unspecified), DisplayName = "Madrid", WorkPeriodStartDate = new DateTime(2001, 1, 3, 3, 18, 35, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("759ec8f8-af40-4e3c-ada1-80aad475545e"), BirthDate = new DateTime(1964, 10, 27, 13, 47, 30, 0, DateTimeKind.Unspecified), DisplayName = "Mercey Brothers", WorkPeriodStartDate = new DateTime(2002, 11, 13, 23, 31, 58, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("24433f12-cc96-4ea3-b3cb-041b1e407e1e"), BirthDate = new DateTime(1963, 4, 20, 7, 12, 20, 0, DateTimeKind.Unspecified), DisplayName = "Fleetwood Mac", WorkPeriodStartDate = new DateTime(2007, 3, 10, 6, 10, 2, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("f94c41f5-5f0c-40d6-a42a-e3488e07f7d1"), BirthDate = new DateTime(1990, 3, 11, 12, 33, 58, 0, DateTimeKind.Unspecified), DisplayName = "Martha and the Muffins", WorkPeriodStartDate = new DateTime(2014, 10, 7, 13, 56, 7, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("445209ce-5104-4ddc-9d0e-03c776117f6b"), BirthDate = new DateTime(1989, 10, 6, 10, 8, 26, 0, DateTimeKind.Unspecified), DisplayName = "Marianas Trench", WorkPeriodStartDate = new DateTime(2002, 4, 12, 1, 15, 55, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("078c9339-4097-41e4-a718-86a099d94796"), BirthDate = new DateTime(1972, 8, 12, 12, 1, 22, 0, DateTimeKind.Unspecified), DisplayName = "MonkeyJunk", WorkPeriodStartDate = new DateTime(2007, 10, 24, 7, 11, 20, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("91c4975c-8ad8-4672-b705-7320e0071ef0"), BirthDate = new DateTime(2000, 4, 22, 21, 50, 33, 0, DateTimeKind.Unspecified), DisplayName = "LiveonRelease", WorkPeriodStartDate = new DateTime(2004, 5, 2, 14, 7, 26, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b97bf3db-6400-4465-a00a-d3c02563089e"), BirthDate = new DateTime(1983, 5, 9, 4, 1, 8, 0, DateTimeKind.Unspecified), DisplayName = "Leahy", WorkPeriodStartDate = new DateTime(2016, 3, 3, 11, 15, 7, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("4c71633b-a14c-40b5-adc9-e948b0abd049"), BirthDate = new DateTime(1997, 1, 18, 5, 45, 44, 0, DateTimeKind.Unspecified), DisplayName = "Low Level Flight", WorkPeriodStartDate = new DateTime(2002, 7, 4, 14, 58, 36, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b82c40f5-6743-4ce9-9753-a2825b96c628"), BirthDate = new DateTime(1981, 3, 30, 0, 35, 23, 0, DateTimeKind.Unspecified), DisplayName = "Luther Wright and the Wrongs", WorkPeriodStartDate = new DateTime(2001, 12, 7, 16, 44, 21, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("584fd455-0b35-4532-8d2f-a149a76dfcfa"), BirthDate = new DateTime(1993, 3, 23, 2, 50, 10, 0, DateTimeKind.Unspecified), DisplayName = "Mobile", WorkPeriodStartDate = new DateTime(2015, 9, 18, 14, 25, 21, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("67524b61-4735-4518-be06-a4b9dceec640"), BirthDate = new DateTime(1964, 9, 27, 20, 51, 41, 0, DateTimeKind.Unspecified), DisplayName = "The Lowest of the Low", WorkPeriodStartDate = new DateTime(2006, 7, 5, 0, 57, 37, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("df808302-c274-4943-b265-17502a3931c3"), BirthDate = new DateTime(1972, 11, 6, 8, 1, 51, 0, DateTimeKind.Unspecified), DisplayName = "Olivia Newton-John", WorkPeriodStartDate = new DateTime(2003, 1, 13, 7, 14, 37, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("717cd2f9-50cf-444b-a46b-8a4f623ae792"), BirthDate = new DateTime(1965, 4, 30, 0, 56, 3, 0, DateTimeKind.Unspecified), DisplayName = "Lee Harvey Osmond", WorkPeriodStartDate = new DateTime(2014, 6, 23, 10, 15, 15, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("3315cab4-49e0-48fb-8d73-d65d797f7c1b"), BirthDate = new DateTime(1978, 5, 13, 10, 6, 29, 0, DateTimeKind.Unspecified), DisplayName = "Malajube", WorkPeriodStartDate = new DateTime(2010, 5, 15, 21, 5, 45, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b3fb81f8-14b7-4d63-bfcd-67e28e9d967f"), BirthDate = new DateTime(1984, 12, 6, 5, 40, 44, 0, DateTimeKind.Unspecified), DisplayName = "The Doors", WorkPeriodStartDate = new DateTime(2001, 2, 6, 7, 41, 41, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("17aedc67-6f6e-4741-a6d3-554a03a2362b"), BirthDate = new DateTime(1980, 12, 17, 20, 49, 56, 0, DateTimeKind.Unspecified), DisplayName = "Michael Jackson", WorkPeriodStartDate = new DateTime(2015, 7, 1, 22, 18, 4, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b526658f-f5da-4e95-a2d2-98a77d21b237"), BirthDate = new DateTime(1970, 12, 30, 9, 12, 46, 0, DateTimeKind.Unspecified), DisplayName = "Malhavoc", WorkPeriodStartDate = new DateTime(2014, 5, 16, 15, 3, 8, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("948b2185-f94c-4452-9b1d-2082f1e3be0c"), BirthDate = new DateTime(1982, 9, 13, 7, 54, 24, 0, DateTimeKind.Unspecified), DisplayName = "ABBA", WorkPeriodStartDate = new DateTime(2012, 7, 17, 5, 19, 22, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("009be40e-0053-4a5e-8969-0e3c67e017d7"), BirthDate = new DateTime(1985, 1, 8, 13, 7, 20, 0, DateTimeKind.Unspecified), DisplayName = "The Mark Inside", WorkPeriodStartDate = new DateTime(2010, 5, 21, 8, 28, 17, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("53735359-03f1-4098-a9e4-1d2c27f0b2b5"), BirthDate = new DateTime(1978, 4, 11, 1, 46, 36, 0, DateTimeKind.Unspecified), DisplayName = "MCJ & Cool G", WorkPeriodStartDate = new DateTime(2005, 4, 30, 7, 29, 21, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("88ef7259-3ef2-4336-ad37-8d4f5680b285"), BirthDate = new DateTime(1998, 7, 6, 14, 11, 3, 0, DateTimeKind.Unspecified), DisplayName = "Lava Hay", WorkPeriodStartDate = new DateTime(2018, 1, 4, 3, 55, 1, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("48c637db-16f0-4e2d-9488-5a8a4c06d23f"), BirthDate = new DateTime(1982, 3, 4, 20, 15, 53, 0, DateTimeKind.Unspecified), DisplayName = "Mudmen", WorkPeriodStartDate = new DateTime(2010, 4, 15, 22, 56, 58, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("1fc2a587-57ea-456a-b970-840ccd143689"), BirthDate = new DateTime(1978, 9, 7, 22, 57, 3, 0, DateTimeKind.Unspecified), DisplayName = "The McDades", WorkPeriodStartDate = new DateTime(2002, 5, 31, 3, 17, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("2bd1b1cd-d0bb-4311-a303-6b404aa5edf0"), BirthDate = new DateTime(2000, 2, 18, 10, 54, 24, 0, DateTimeKind.Unspecified), DisplayName = "Merlin", WorkPeriodStartDate = new DateTime(2016, 7, 30, 5, 57, 51, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("4df9ec0c-de59-4bd0-b285-6766bc88679c"), BirthDate = new DateTime(1987, 4, 27, 15, 23, 5, 0, DateTimeKind.Unspecified), DisplayName = "Bryan Adams", WorkPeriodStartDate = new DateTime(2015, 4, 25, 13, 49, 56, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b4fbb1e4-6e2a-4766-b091-8e291d5cd162"), BirthDate = new DateTime(1999, 3, 17, 3, 36, 31, 0, DateTimeKind.Unspecified), DisplayName = "Chicago", WorkPeriodStartDate = new DateTime(2001, 1, 4, 10, 51, 8, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("7c878507-f096-4c97-aa62-8cced879ae2b"), BirthDate = new DateTime(1969, 7, 21, 5, 57, 39, 0, DateTimeKind.Unspecified), DisplayName = "The Rolling Stones", WorkPeriodStartDate = new DateTime(2015, 2, 9, 2, 39, 48, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("4863949e-30a8-40bd-a2a1-79349f74eabf"), BirthDate = new DateTime(1970, 9, 16, 17, 54, 3, 0, DateTimeKind.Unspecified), DisplayName = "Loco Locass", WorkPeriodStartDate = new DateTime(2015, 8, 5, 1, 50, 7, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d6a41449-6c6c-43f2-b22c-0e35f8d0081b"), BirthDate = new DateTime(1966, 12, 24, 16, 44, 19, 0, DateTimeKind.Unspecified), DisplayName = "Elvis Presley", WorkPeriodStartDate = new DateTime(2009, 5, 27, 8, 24, 2, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d185cc17-ab73-4bab-8ada-fefeee6446ef"), BirthDate = new DateTime(1963, 2, 6, 7, 18, 57, 0, DateTimeKind.Unspecified), DisplayName = "Farm Fresh", WorkPeriodStartDate = new DateTime(2000, 8, 29, 5, 46, 55, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("43c004b0-cd0a-479a-986a-a9a347d34eff"), BirthDate = new DateTime(1993, 5, 23, 1, 42, 20, 0, DateTimeKind.Unspecified), DisplayName = "The Marble Index", WorkPeriodStartDate = new DateTime(2018, 11, 24, 2, 10, 24, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("c9b0ee7d-7ade-432d-802c-4be6c4403ad0"), BirthDate = new DateTime(1986, 4, 25, 4, 27, 27, 0, DateTimeKind.Unspecified), DisplayName = "Leigh Ashford", WorkPeriodStartDate = new DateTime(2015, 10, 22, 5, 22, 34, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("45f34f0c-6132-4a8e-915e-ee8a300e8692"), BirthDate = new DateTime(1985, 10, 26, 23, 18, 51, 0, DateTimeKind.Unspecified), DisplayName = "Linda Ronstadt", WorkPeriodStartDate = new DateTime(2001, 6, 21, 17, 58, 23, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("58e4d499-c16f-4f09-a2af-7b64b26a58e6"), BirthDate = new DateTime(1983, 9, 24, 17, 40, 19, 0, DateTimeKind.Unspecified), DisplayName = "Pink Floyd", WorkPeriodStartDate = new DateTime(2007, 12, 3, 12, 21, 45, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("548ed61e-2f2e-4c32-aa0b-1142237743f9"), BirthDate = new DateTime(1967, 5, 2, 12, 35, 25, 0, DateTimeKind.Unspecified), DisplayName = "Love Kills", WorkPeriodStartDate = new DateTime(2012, 5, 27, 4, 18, 18, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("70a913de-55a9-4f5a-9f6d-e369dcf62060"), BirthDate = new DateTime(1994, 8, 13, 23, 27, 24, 0, DateTimeKind.Unspecified), DisplayName = "Queen", WorkPeriodStartDate = new DateTime(2014, 10, 18, 1, 17, 33, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("6a66a994-16c5-465e-9b98-8e03cba3ea5c"), BirthDate = new DateTime(1978, 2, 18, 3, 41, 15, 0, DateTimeKind.Unspecified), DisplayName = "Longing for Dawn", WorkPeriodStartDate = new DateTime(2000, 2, 14, 19, 25, 36, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("deda0b7e-9543-4fbf-82ce-6d01122dc65c"), BirthDate = new DateTime(1966, 3, 9, 7, 19, 41, 0, DateTimeKind.Unspecified), DisplayName = "Moneen", WorkPeriodStartDate = new DateTime(2015, 10, 21, 13, 10, 54, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d4f415f1-89ff-46db-94cf-b35361cb2d8d"), BirthDate = new DateTime(1975, 6, 8, 17, 57, 36, 0, DateTimeKind.Unspecified), DisplayName = "Leslie Spit Treeo", WorkPeriodStartDate = new DateTime(2016, 4, 19, 22, 19, 52, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("30917fbf-f4f2-4a50-b211-c1edee3fa7a1"), BirthDate = new DateTime(2000, 12, 6, 15, 13, 38, 0, DateTimeKind.Unspecified), DisplayName = "Whitney Houston", WorkPeriodStartDate = new DateTime(2005, 4, 7, 16, 58, 19, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("a89ac573-289e-40a2-9baf-a5dd4d4ed3a2"), BirthDate = new DateTime(1974, 3, 15, 10, 13, 3, 0, DateTimeKind.Unspecified), DisplayName = "Prince", WorkPeriodStartDate = new DateTime(2011, 10, 26, 5, 49, 18, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("115e9f9d-68d5-4781-bafe-64c6633dce0e"), BirthDate = new DateTime(1968, 4, 20, 6, 28, 48, 0, DateTimeKind.Unspecified), DisplayName = "Stevie Wonder", WorkPeriodStartDate = new DateTime(2002, 5, 11, 21, 40, 23, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b60a6952-56a9-4d11-a881-bb4414f5e7be"), BirthDate = new DateTime(1974, 1, 16, 9, 42, 40, 0, DateTimeKind.Unspecified), DisplayName = "Marilyn's Vitamins", WorkPeriodStartDate = new DateTime(2006, 3, 27, 23, 6, 3, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("32d9dace-8e74-4055-ac14-dc7b494c36e7"), BirthDate = new DateTime(1993, 10, 23, 16, 40, 40, 0, DateTimeKind.Unspecified), DisplayName = "The MRQ", WorkPeriodStartDate = new DateTime(2003, 4, 2, 1, 22, 19, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("27943181-1947-4065-90a5-0fb363e0e958"), BirthDate = new DateTime(1962, 7, 21, 5, 16, 45, 0, DateTimeKind.Unspecified), DisplayName = "Men Without Hats", WorkPeriodStartDate = new DateTime(2003, 1, 10, 12, 54, 57, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("4b12c0f8-0855-45f2-b49a-0317658a1624"), BirthDate = new DateTime(1976, 7, 26, 6, 48, 44, 0, DateTimeKind.Unspecified), DisplayName = "Lost Dakotas", WorkPeriodStartDate = new DateTime(2006, 4, 23, 18, 24, 27, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("4a4a8625-2066-4488-bb2a-d29261108761"), BirthDate = new DateTime(1999, 1, 13, 21, 13, 56, 0, DateTimeKind.Unspecified), DisplayName = "Mystery", WorkPeriodStartDate = new DateTime(2006, 1, 3, 16, 32, 26, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("686b158f-97ef-4d9a-a50c-beca0b15e64f"), BirthDate = new DateTime(1964, 9, 6, 14, 0, 56, 0, DateTimeKind.Unspecified), DisplayName = "The Moffatts", WorkPeriodStartDate = new DateTime(2000, 12, 11, 15, 1, 4, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d27e6f6b-152a-4db7-943e-f9de0d81d8c6"), BirthDate = new DateTime(1995, 5, 13, 15, 51, 30, 0, DateTimeKind.Unspecified), DisplayName = "Mecca Normal", WorkPeriodStartDate = new DateTime(2004, 6, 15, 4, 26, 51, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("d4848e08-0d45-4dab-ae62-c02495eb3b2d"), BirthDate = new DateTime(1980, 7, 13, 2, 51, 59, 0, DateTimeKind.Unspecified), DisplayName = "L'Étranger", WorkPeriodStartDate = new DateTime(2010, 12, 10, 5, 52, 2, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("3e820e2e-6594-4c5a-aa94-c2d54313493a"), BirthDate = new DateTime(1961, 6, 6, 7, 24, 6, 0, DateTimeKind.Unspecified), DisplayName = "Mercy, the Sexton", WorkPeriodStartDate = new DateTime(2007, 6, 14, 6, 13, 30, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("0795f9e8-7320-4bd0-b465-c8b1253c8852"), BirthDate = new DateTime(1980, 9, 29, 18, 22, 1, 0, DateTimeKind.Unspecified), DisplayName = "Mean Red Spiders", WorkPeriodStartDate = new DateTime(2009, 9, 3, 14, 34, 25, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("758f9b2b-20e5-4094-b151-4e8d5def8b0f"), BirthDate = new DateTime(1984, 5, 23, 19, 55, 50, 0, DateTimeKind.Unspecified), DisplayName = "B'z", WorkPeriodStartDate = new DateTime(2016, 12, 3, 11, 40, 34, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("b6d81bbc-0378-4604-a185-95363f30578b"), BirthDate = new DateTime(1990, 4, 3, 13, 3, 56, 0, DateTimeKind.Unspecified), DisplayName = "The Mahones", WorkPeriodStartDate = new DateTime(2004, 7, 8, 22, 41, 46, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("9a4f2f1f-6bf9-4f97-8bbb-47dcf2c410e4"), BirthDate = new DateTime(1990, 9, 1, 21, 22, 12, 0, DateTimeKind.Unspecified), DisplayName = "Maow", WorkPeriodStartDate = new DateTime(2000, 3, 16, 14, 35, 45, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("7ca19b96-e17a-422c-aa18-eb5b3100b9c6"), BirthDate = new DateTime(1963, 5, 29, 7, 31, 0, 0, DateTimeKind.Unspecified), DisplayName = "Monster Voodoo Machine", WorkPeriodStartDate = new DateTime(2012, 12, 12, 9, 31, 54, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("9b3800ba-c90a-47fa-b9aa-d99a18990c24"), BirthDate = new DateTime(1973, 6, 27, 21, 0, 32, 0, DateTimeKind.Unspecified), DisplayName = "Mahogany Rush", WorkPeriodStartDate = new DateTime(2012, 2, 16, 10, 58, 39, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("1ced908f-719d-4573-b4c7-602509ea38d7"), BirthDate = new DateTime(1993, 2, 15, 16, 36, 5, 0, DateTimeKind.Unspecified), DisplayName = "Metallica", WorkPeriodStartDate = new DateTime(2001, 7, 9, 8, 6, 23, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("f9bdeed2-fded-4eab-a759-2c89d4fb795d"), BirthDate = new DateTime(1966, 1, 1, 10, 37, 6, 0, DateTimeKind.Unspecified), DisplayName = "The Matadors", WorkPeriodStartDate = new DateTime(2009, 8, 5, 5, 10, 56, 0, DateTimeKind.Unspecified) },
                        new { Id = new Guid("81826d1b-d350-45ca-80a5-c5a1ee0fbb87"), BirthDate = new DateTime(1985, 12, 30, 9, 56, 43, 0, DateTimeKind.Unspecified), DisplayName = "Moist", WorkPeriodStartDate = new DateTime(2016, 9, 23, 15, 38, 11, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("Models.EntityModels.User", b =>
                {
                    b.HasOne("Models.EntityModels.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId");
                });
#pragma warning restore 612, 618
        }
    }
}
